const assert = require('assert/strict');
const { launch, ROOT, out } = require('./lib');
(async () => {
  const b = await launch();
  const p = await b.newPage({ viewport: { width: 1000, height: 700 } });
  const errors = [];
  p.on('pageerror', e => errors.push(e.message));
  await p.goto(ROOT + '/samples/persistent-sidebar.html?article=sidebar&pane=detail');
  await p.waitForFunction(() => window.pudlMd);
  const state = () => p.evaluate(() => pudlMd.state(document.querySelector('.md-layout')));
  const command = action => p.evaluate(a => pudlMd.command(document.querySelector('.md-layout'), a), action);
  const handle = p.locator('.md-resize');
  const drag = async (delta, cancel = false) => {
    const r = await handle.boundingBox();
    await p.mouse.move(r.x + r.width / 2, r.y + 80);
    await p.mouse.down();
    await p.mouse.move(r.x + r.width / 2 + delta, r.y + 80, { steps: 5 });
    if (cancel) await handle.dispatchEvent('pointercancel', { pointerId: await p.evaluate(() => window.lastPointerId) });
    await p.mouse.up();
  };
  await p.evaluate(() => {
    document.addEventListener('pointerdown', e => { window.lastPointerId = e.pointerId; }, true);
    window.changes = []; window.resizes = []; window.requests = [];
    document.addEventListener('pudl:md-change', e => changes.push(e.detail));
    document.addEventListener('pudl:md-resize', e => resizes.push(e.detail));
    document.addEventListener('pudl:md-request', e => requests.push(e.detail));
    window.originalInput = document.querySelector('#list-notes');
  });
  assert.equal((await state()).width, 260);
  assert.equal((await handle.boundingBox()).width, 12);
  await p.locator('#list-notes').focus();
  await command('collapse');
  assert.equal((await state()).width, 260);
  assert.equal((await state()).effectiveWidth, 0);
  assert.equal(await handle.evaluate(h => document.activeElement === h), true);
  assert.equal(await p.locator('.md-sidebar').evaluate(e => e.inert), true);
  await handle.press('Enter');
  assert.equal((await state()).effectiveWidth, 260);
  assert.equal(await p.locator('.md-sidebar').evaluate(e => e.inert), false);
  await drag(70);
  assert.equal((await state()).width, 330);
  const events = await p.evaluate(() => changes.length);
  await drag(50, true);
  assert.equal((await state()).width, 330);
  assert.equal(await p.evaluate(() => changes.length), events);
  await drag(-320);
  assert.equal((await state()).collapsed, true);
  assert.equal((await state()).width, 330);
  await drag(210);
  assert.equal((await state()).collapsed, false);
  assert.equal((await state()).width, 210);
  await command('reset');
  await p.locator('[data-md-action="increase"]').click();
  assert.equal((await state()).width, 276);
  await handle.focus(); await handle.press('Shift+ArrowRight');
  assert.equal((await state()).width, 340);
  await p.evaluate(() => document.querySelector('.md-layout').dir = 'rtl');
  await handle.press('ArrowLeft');
  assert.equal((await state()).width, 356);
  await drag(-30);
  assert.equal((await state()).width, 386);
  await p.evaluate(() => document.querySelector('.md-layout').dir = 'ltr');

  // A container transition cancels the gesture and preserves requested width.
  const r = await handle.boundingBox();
  await p.mouse.move(r.x + r.width / 2, r.y + 80); await p.mouse.down();
  await p.mouse.move(r.x + 50, r.y + 80);
  await p.evaluate(() => document.querySelector('.md-layout').style.width = '500px');
  await p.waitForFunction(() => document.querySelector('.md-layout').hasAttribute('data-md-narrow'));
  await p.mouse.up();
  assert.equal((await state()).width, 386);
  assert.equal((await state()).pane, 'detail');
  assert.equal((await state()).effectiveWidth, 0);
  assert.equal(await handle.isVisible(), true);
  await drag(30);
  assert.equal((await state()).pane, 'list');
  assert.equal((await state()).effectiveWidth, 500 - 12);
  assert.equal((await state()).width, 386);
  await p.locator('#list-notes').fill('Mounted');
  await drag(-10);
  assert.equal((await state()).pane, 'list');
  await drag(-40, true);
  assert.equal((await state()).pane, 'list');
  await drag(-30);
  assert.equal((await state()).pane, 'detail');
  await p.goBack();
  assert.equal((await state()).pane, 'list');
  await p.goForward();
  assert.equal((await state()).pane, 'detail');
  assert.equal(await p.evaluate(() => originalInput === document.querySelector('#list-notes')), true);
  assert.equal(await p.locator('#list-notes').inputValue(), 'Mounted');
  await p.evaluate(() => document.querySelector('.md-layout').dir = 'rtl');
  await drag(-30);
  assert.equal((await state()).pane, 'list');
  await drag(30);
  assert.equal((await state()).pane, 'detail');
  await p.evaluate(() => { document.querySelector('.md-layout').dir = 'ltr'; document.querySelector('.md-layout').style.width = ''; });
  assert.equal((await state()).width, 386);
  assert.equal((await state()).effectiveWidth, 386);

  // Host refusal and stale asynchronous completions do not change presentation.
  await p.setViewportSize({ width: 500, height: 700 });
  await p.goto(ROOT + '/samples/persistent-sidebar.html');
  await p.waitForFunction(() => window.pudlMd);
  await command('collapse');
  assert.equal((await state()).pane, 'list');
  assert.equal(new URL(p.url()).search, '');
  const result = await p.evaluate(() => {
    const el = document.querySelector('.md-layout');
    let id;
    el.addEventListener('pudl:md-request', e => { id = e.detail.requestId; });
    pudlMd.command(el, 'collapse');
    const stale = id;
    pudlMd.command(el, 'collapse');
    const rejected = pudlMd.setPane(el, 'detail', stale);
    const accepted = pudlMd.setPane(el, 'detail', id);
    const duplicate = pudlMd.setPane(el, 'list', id);
    return { rejected, accepted, duplicate };
  });
  assert.deepEqual(result, { rejected: false, accepted: true, duplicate: false });
  await p.locator('#article-notes').focus();
  await p.evaluate(() => pudlMd.setPane(document.querySelector('.md-layout'), 'list'));
  assert.equal(await handle.evaluate(h => h === document.activeElement), true);
  assert.equal(await p.locator('.md-detail').evaluate(e => e.inert), true);
  assert.equal(await handle.getAttribute('aria-valuenow'), '100');
  await p.evaluate(() => document.querySelector('.md-sidebar').inert = true);
  await p.evaluate(() => pudlMd.setPane(document.querySelector('.md-layout'), 'detail'));
  await p.evaluate(() => pudlMd.setPane(document.querySelector('.md-layout'), 'list'));
  assert.equal(await p.locator('.md-sidebar').evaluate(e => e.inert), true);
  // Independent components preserve state and release inert ownership on removal.
  await p.setViewportSize({ width: 1000, height: 700 });
  const independent = await p.evaluate(() => {
    const original = document.querySelector('.md-layout');
    const el = original.cloneNode(true);
    el.querySelectorAll('[id]').forEach(n => n.removeAttribute('id'));
    el.style.setProperty('--md-sidebar-w', '20rem');
    el.setAttribute('data-md-min', '40');
    el.setAttribute('data-md-max', '400');
    document.body.append(el);
    pudlMd.refresh();
    pudlMd.command(el, 'collapse');
    const first = pudlMd.state(original);
    const second = pudlMd.state(el);
    pudlMd.command(el, 'expand');
    const restored = pudlMd.state(el);
    el.remove(); pudlMd.refresh();
    return { first, second, restored, gone: pudlMd.state(el) };
  });
  assert.equal(independent.first.collapsed, false);
  assert.equal(independent.second.collapsed, true);
  assert.equal(independent.second.width, independent.restored.width);
  assert.equal(independent.restored.effectiveWidth, independent.restored.width);
  assert.equal(independent.gone, null);
  // Losing capture rolls back, including the rendered accessible width.
  await p.evaluate(() => document.addEventListener('pointerdown', e => { window.lastPointerId = e.pointerId; }, true));
  await command('reset');
  const lost = await handle.boundingBox();
  await p.mouse.move(lost.x + lost.width / 2, lost.y + 80); await p.mouse.down();
  await p.mouse.move(lost.x + 70, lost.y + 80);
  await handle.evaluate(h => h.releasePointerCapture(window.lastPointerId));
  await p.mouse.up();
  assert.equal((await state()).width, 260);
  assert.equal(await handle.getAttribute('aria-valuenow'), '260');
  await p.setViewportSize({ width: 500, height: 700 });
  await p.screenshot({ path: out('persistent-sidebar-narrow.png') });
  await p.setViewportSize({ width: 1000, height: 700 });
  await p.evaluate(() => pudlSetTheme('light'));
  await p.screenshot({ path: out('persistent-sidebar-light.png') });
  await p.evaluate(() => pudlSetTheme('dark'));
  await p.screenshot({ path: out('persistent-sidebar-dark.png') });
  await p.emulateMedia({ forcedColors: 'active' });
  await p.screenshot({ path: out('persistent-sidebar-forced.png') });
  // Legacy pointer cancellation must also preserve the original width.
  await p.emulateMedia({ forcedColors: 'none' });
  await p.goto(ROOT + '/reference.html');
  const legacy = p.locator('.layout-demo .md-resize').first();
  await legacy.scrollIntoViewIfNeeded();
  await p.evaluate(() => document.addEventListener('pointerdown', e => { window.lastPointerId = e.pointerId; }, true));
  const legacyWidth = await p.locator('.layout-demo .md-sidebar').first().evaluate(e => e.getBoundingClientRect().width);
  const lr = await legacy.boundingBox();
  await p.mouse.move(lr.x + 3, lr.y + 70); await p.mouse.down();
  await p.mouse.move(lr.x + 70, lr.y + 70);
  await legacy.dispatchEvent('pointercancel', { pointerId: await p.evaluate(() => lastPointerId) });
  await p.mouse.up();
  assert.equal(await p.locator('.layout-demo .md-sidebar').first().evaluate(e => e.getBoundingClientRect().width), legacyWidth);
  assert.deepEqual(errors, []);
  await b.close();
  console.log('PASS persistent sidebar state, gestures, URL navigation, focus, RTL, cancellation and host refusal');
})().catch(e => { console.error('FAIL ' + e.message.replace(/\n/g, ' ') + ' ' + e.stack.split('\n').find(line => line.includes('.test.js:'))); process.exit(1); });
