const { launch, ROOT, out } = require('./lib');
const { AxeBuilder } = require('@axe-core/playwright');
let failures = 0;
function check(name, ok, detail) {
  console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail ? ' ' + JSON.stringify(detail) : ''));
  if (!ok) failures++;
}
(async () => {
  const browser = await launch();
  const context = await browser.newContext({ viewport: { width: 1400, height: 850 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(ROOT + '/samples/shared-docks.html');
  await page.waitForSelector('[data-dock-key="workspace"]');
  check('default docks keep the plain address', await page.evaluate(() => location.search === ''));
  const win = key => page.locator('.win[data-win="' + key + '"]');
  const tab = key => page.locator('[data-dock-key="' + key + '"]');
  const mode = (edge, value) => page.evaluate(([e, v]) => pudlWindows.dockMode(e, v), [edge, value]);
  const box = selector => page.locator(selector).boundingBox();
  check('required windows appear first in their dock', await page.locator('[data-dock-edge="left"] [role="tab"]').first().getAttribute('data-dock-key') === 'workspace');
  check('the two docks select independently', await win('chats').isVisible() || await win('workspace').isVisible());
  const left = await box('[data-dock-edge="left"]'), note = await win('note').boundingBox();
  check('the maximized window leaves room for both docks', note.x >= left.width && note.width < 800, { left, note });
  for (const edge of ['left', 'right']) {
    const toggle = page.locator('[data-dock-edge="' + edge + '"] .win-dock-toggle');
    const before = await toggle.boundingBox();
    await toggle.click();
    const after = await toggle.boundingBox();
    check('the ' + edge + ' Collapse and Pin buttons keep the same position', Math.abs(before.x - after.x) < .5 && Math.abs(before.y - after.y) < .5, { before, after });
    const firstTab = await page.locator('[data-dock-edge="' + edge + '"] [role="tab"]').first().boundingBox();
    check('the ' + edge + ' rail puts Pin above its tabs', after.y + after.height <= firstTab.y);
    await toggle.click();
    await mode(edge, 'auto');
  }
  await tab('chats').click();
  await page.locator('#chat-search').fill('Keep this draft');
  await tab('workspace').click();
  await tab('chats').click();
  check('switching tabs preserves mounted content', await page.locator('#chat-search').inputValue() === 'Keep this draft');
  check('a tabbed dock omits the window title bar', !(await win('chats').locator('.win-head').isVisible()));
  const oldWidth = (await win('chats').boundingBox()).width;
  const grip = await win('chats').locator('.win-rh[data-edge="e"]').boundingBox();
  await page.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2);
  await page.mouse.down();
  await page.mouse.move(grip.x + grip.width / 2 + 60, grip.y + grip.height / 2, { steps: 5 });
  await page.mouse.up();
  const sharedWidth = (await win('chats').boundingBox()).width;
  await tab('workspace').click();
  check('resizing one dock tab changes every tab width', sharedWidth > oldWidth + 40 && Math.abs((await win('workspace').boundingBox()).width - sharedWidth) < 2);
  await page.reload();
  await tab('chats').click();
  check('the shared dock width survives reload', Math.abs((await win('chats').boundingBox()).width - sharedWidth) < 2);
  await page.locator('[data-dock-menu="chats"]').click();
  await page.waitForSelector('#win-menu-chats:popover-open');
  check('the tab menu exposes the ordinary window commands', await page.locator('#win-menu-chats [data-win-cmd="close"]').isVisible());
  await page.keyboard.press('Escape');
  check('Escape returns focus to the tab menu button', await page.locator('[data-dock-menu="chats"]').evaluate(el => el === document.activeElement));
  await tab('workspace').click();
  await tab('chats').focus();
  await page.keyboard.press('Shift+F10');
  await page.waitForSelector('#win-menu-chats:popover-open');
  check('the context-menu key reveals an inactive dock tab', await win('chats').isVisible());
  await page.keyboard.press('Escape');
  await page.evaluate(() => { pudlWindows.dock('workspace', null); pudlWindows.snap('workspace', 'right'); });
  check('a dock-only sidebar refuses floating and snapping', await page.evaluate(() => pudlWindows.state().place.workspace.mode === 'dock-left'));
  await tab('workspace').focus();
  await page.keyboard.press('ArrowRight');
  check('arrows move focus without selecting', await tab('chats').evaluate(el => el === document.activeElement));
  await page.keyboard.press('Home');
  await page.keyboard.press('Enter');
  check('Enter selects the focused tab', await win('workspace').isVisible() && !(await win('chats').isVisible()));
  check('required windows have no close affordance', await tab('workspace').locator('.doc-tab-close').count() === 0 && !(await win('workspace').locator('[data-win-action="close"]').isVisible()));
  await page.locator('[data-dock-menu="workspace"]').click();
  await page.waitForSelector('#win-menu-workspace:popover-open');
  check('a required sidebar menu keeps docking commands and omits Close', await page.locator('#win-menu-workspace [data-win-cmd="close"]').count() === 0 && await page.locator('#win-menu-workspace [data-win-cmd="dock:right"]').isVisible());
  await page.keyboard.press('Escape');
  await page.evaluate(() => { pudlWindows.close('workspace'); pudlWindows.replace('workspace', 'note'); pudlWindows.rekey('workspace', 'other'); });
  check('public close, replacement and rekey preserve required windows', await win('workspace').count() === 1 && await page.evaluate(() => !pudlWindows.menuCommands('workspace').some(c => c.id === 'close')));
  await tab('workspace').focus();
  await page.keyboard.press('Delete');
  check('Delete preserves required windows', await win('workspace').count() === 1);
  await tab('chats').focus();
  await page.evaluate(() => {
    const el = document.querySelector('.win[data-win="chats"]');
    el.addEventListener('pudl:window-closing', e => e.preventDefault(), { once: true });
  });
  await page.keyboard.press('Delete');
  check('a dirty applet can refuse tab closure', await win('chats').count() === 1);
  await page.evaluate(() => document.querySelector('.win[data-win="chats"]').setAttribute('data-win-attention', '7'));
  await page.waitForFunction(() => document.querySelector('[data-dock-key="chats"]').getAttribute('aria-label').includes('7'));
  check('live status updates preserve tab focus', await tab('chats').evaluate(el => el === document.activeElement));
  check('taskbar and side tab show the same attention count', await page.locator('[data-win-tab="chats"] .win-item-attention').textContent() === '7');
  await page.evaluate(() => document.querySelector('.win[data-win="chats"]').setAttribute('data-win-progress', '42'));
  await page.waitForFunction(() => document.querySelector('[data-win-tab="chats"] .win-item-progress').textContent === '42%');
  check('progress appears in the taskbar and tab name', (await tab('chats').getAttribute('aria-label')).includes('42%'));
  await tab('workspace').click();
  await page.locator('#editor').click();
  await page.reload();
  await page.waitForSelector('[data-dock-key="workspace"]');
  check('the dock selection survives reloading with a different front window', await win('workspace').isVisible() && !(await win('chats').isVisible()));
  await page.evaluate(() => { pudlWindows.minimizeAll(); });
  check('Minimize All collapses shared docks to rails', await page.locator('[data-dock-rail]').count() === 2 && !(await win('note').isVisible()));
  await page.evaluate(() => { pudlWindows.restoreAll(); });
  check('Restore All preserves the previous dock preferences', await win('workspace').isVisible() && await win('note').isVisible() && await page.evaluate(() => pudlWindows.state().docks.left.mode === 'auto'));
  await page.evaluate(() => document.documentElement.dataset.theme = 'light');
  await page.screenshot({ path: out('shared-docks-light.png') });
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
  await page.screenshot({ path: out('shared-docks-dark.png') });
  const accessibility = await new AxeBuilder({ page }).withRules(['aria-allowed-attr', 'aria-allowed-role', 'aria-valid-attr-value', 'aria-required-children', 'aria-required-parent', 'button-name']).analyze();
  check('shared docks satisfy the ARIA rules', accessibility.violations.length === 0, accessibility.violations.map(v => v.id));
  await page.setViewportSize({ width: 800, height: 700 });
  await page.waitForSelector('[data-dock-edge="left"][data-dock-rail]');
  check('both side docks become icon rails when narrow', await page.locator('[data-dock-rail]').count() === 2 && !(await win('workspace').isVisible()));
  check('rail buttons match Pin in both dimensions', await page.locator('[data-dock-rail]').evaluateAll(groups => groups.every(group => {
    const pin = group.querySelector('.win-dock-toggle').getBoundingClientRect();
    return [...group.querySelectorAll('[role="tab"]')].every(tab => { const r = tab.getBoundingClientRect(); return r.width === pin.width && r.height === pin.height; });
  })));
  check('Workspace has no rail dropdown', !await page.locator('[data-dock-menu="workspace"]').isVisible());
  check('retracted rail buttons are raised', await page.locator('[data-dock-rail] [data-dock-peek]').count() === 0);
  const before = await win('note').boundingBox();
  const canonical = await page.evaluate(() => JSON.stringify(pudlWindows.state().place));
  await tab('workspace').click();
  check('a rail opens its window over the central area', await win('workspace').isVisible() && JSON.stringify(await win('note').boundingBox()) === JSON.stringify(before));
  check('the flyout button remains depressed', await tab('workspace').evaluate(el => el.hasAttribute('data-dock-peek') && getComputedStyle(el).boxShadow.includes('inset')));
  await page.locator('#workspace-search').fill('Still mounted');
  await page.screenshot({ path: out('shared-docks-rail.png') });
  await page.keyboard.press('Escape');
  check('Escape retracts the slideout and restores its tab focus', !(await win('workspace').isVisible()) && await tab('workspace').evaluate(el => el === document.activeElement));
  check('retracting releases the rail button', !await tab('workspace').evaluate(el => el.hasAttribute('data-dock-peek')));
  await tab('workspace').click();
  check('a sidebar slideout still has no window title bar', !(await win('workspace').locator('.win-head').isVisible()));
  await tab('workspace').focus();
  await page.keyboard.press('Shift+F10');
  await page.waitForSelector('.win-menu:popover-open');
  check('a slideout stays open while using its menu', await win('workspace').isVisible());
  await page.keyboard.press('Escape');
  check('Escape first closes the menu', await win('workspace').isVisible());
  await page.locator('#editor').click();
  check('working elsewhere retracts an unpinned slideout', !(await win('workspace').isVisible()));
  await tab('workspace').click();
  await page.locator('[data-dock-edge="left"] .win-dock-toggle').click();
  await page.locator('#editor').click();
  check('pinning keeps the dock open', await win('workspace').isVisible() && await page.evaluate(() => pudlWindows.state().docks.left.mode === 'open'));
  await mode('left', 'auto');
  check('rail interactions preserve canonical window placement', canonical === await page.evaluate(() => JSON.stringify(pudlWindows.state().place)));
  await page.setViewportSize({ width: 1400, height: 850 });
  await page.waitForFunction(() => !document.querySelector('[data-dock-edge="left"]').hasAttribute('data-dock-rail'));
  check('automatic rails reopen when the layer widens', await win('workspace').isVisible() && await page.locator('#workspace-search').inputValue() === 'Still mounted');
  await page.evaluate(() => pudlWindows.dock('workspace', 'right'));
  check('the required window can move to the other side and stays first', await page.locator('[data-dock-edge="right"] [role="tab"]').first().getAttribute('data-dock-key') === 'workspace');
  await page.evaluate(() => { pudlWindows.raise('chats'); pudlWindows.raise('note'); pudlWindows.rekey('chats', 'conversation'); });
  check('rekeying retains a dock selection that is behind the front window', await page.evaluate(() => pudlWindows.state().docks.left.selected === 'conversation'));
  await page.evaluate(() => pudlWindows.rekey('conversation', 'chats'));
  await page.evaluate(() => pudlWindows.dock('chats', null));
  check('undocking restores the window role', await win('chats').getAttribute('role') === 'dialog');
  check('undocking after rekeying preserves a valid accessible label', await win('chats').evaluate(el => !!document.getElementById(el.getAttribute('aria-labelledby'))));
  await page.evaluate(() => pudlWindows.dock('chats', 'left'));
  await tab('chats').focus();
  await page.keyboard.press('Delete');
  check('Delete closes an ordinary tab', await win('chats').count() === 0);
  await page.setViewportSize({ width: 390, height: 720 });
  await tab('workspace').click();
  check('a phone-sized rail and slideout fit without page overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: out('shared-docks-phone.png') });
  await page.goto(ROOT + '/samples/shared-docks.html?open=note');
  await page.waitForSelector('[data-dock-key="workspace"]');
  check('an address cannot omit a required window', await win('workspace').count() === 1);
  await page.route('**/samples/shared-docks.html*', async route => {
    const response = await route.fetch();
    await route.fulfill({ response, body: (await response.text()).replace('data-win-required="workspace"', '') });
  });
  await page.goto(ROOT + '/samples/shared-docks.html');
  await page.waitForSelector('[data-dock-key="workspace"]');
  await page.evaluate(() => {
    pudlWindows.dockMode('left', 'rail');
    pudlWindows.dockMode('right', 'open');
    pudlWindows.state().open.forEach(key => pudlWindows.close(key));
  });
  await page.reload();
  await page.waitForFunction(() => window.pudlWindows && pudlWindows.state().open.length === 0);
  check('empty docks retain their preferences across reloads', await page.evaluate(() => pudlWindows.state().docks.left.mode === 'rail' && pudlWindows.state().docks.right.mode === 'open'));
  check('no page errors occurred', !errors.length, errors);
  await browser.close();
  process.exit(failures ? 1 : 0);
})().catch(err => { console.error(err); process.exit(1); });
